<?xml version="1.0"?>
<!--
Version:  2017.07.31
Authors:  Members of the Team NAIST-Panasonic at the Amazon Robotics Challenge 2017
          Gustavo A. Garcia R. garcia-g at is.naist.jp (Captain), 
          Lotfi El Hafi, Felix von Drigalski, Wataru Yamazaki, Viktor Hoerig, Arnaud Delmotte, 
          Akishige Yuguchi, Marcus Gall, Chika Shiogama, Kenta Toyoshima, Pedro Uriguen, 
          Rodrigo Elizalde, Masaki Yamamoto, Yasunao Okazaki, Kazuo Inoue, Katsuhiko Asai, 
          Ryutaro Futakuchi, Seigo Okada, Yusuke Kato, and Pin-Chu Yang
*******************
Copyright 2017 Team NAIST-Panasonic 
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at 
    http://www.apache.org/licenses/LICENSE-2.0 
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*******************
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="tnp_box">
  
  <xacro:macro name="tnp_box" params="boxname box_w box_l box_h thickness color *origin">
    <!-- The box can either be defined with measurements box_w,l,h or by its size ID (order boxes from amazon) -->

    <link name="${boxname}">
      <!-- w is in x, l is in y, h is in z -->
      <!-- Left side -->
      <visual>
        <origin xyz="${box_w/2} ${box_l+thickness/2} ${box_h/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${box_w+thickness*2} ${thickness} ${box_h}"/> 
        </geometry>
        <material name="${color}"/>
      </visual>
      <!-- Right side -->
      <visual>
        <origin xyz="${box_w/2} ${-thickness/2} ${box_h/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${box_w+thickness*2} ${thickness} ${box_h}"/> 
        </geometry>
        <material name="${color}"/>
      </visual>
      <!-- Front side -->
      <visual>
        <origin xyz="${box_w+thickness/2} ${box_l/2} ${box_h/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${thickness} ${box_l+thickness*2} ${box_h}"/> 
        </geometry>
        <material name="${color}"/>
      </visual>
      <!-- Back side -->
      <visual>
        <origin xyz="-${thickness/2} ${box_l/2} ${box_h/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${thickness} ${box_l+thickness*2} ${box_h}"/> 
        </geometry>
        <material name="${color}"/>
      </visual>
      <!-- Bottom -->
      <visual>
        <origin xyz="${box_w/2} ${box_l/2} -${thickness/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${box_w+thickness*2} ${box_l+thickness*2} ${thickness}"/> 
        </geometry>
        <material name="${color}"/>
      </visual>

    </link>
    <joint name="${boxname}" type="fixed">
      <parent link="world" />
      <child link = "${boxname}" />
      <xacro:insert_block name="origin"/>
    </joint>
  </xacro:macro>
</robot> 
